
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abdullah
 */
public class EmployeeForm extends javax.swing.JFrame {
    
    Validators V = new Validators();
    EmployeeData E;
    private static String ID;
    public static EmployeeData L;
    public String confrm;

    /**
     * Creates new form EmployeeForm
     *
     * @param Employee
     * @param Action
     * @param confirm
     */
    public EmployeeForm(String Employee, String Action, String confirm) {
        initComponents();
        Inventory.getObject().addItemsToComboBox();
        jComboBox1.setModel(new DefaultComboBoxModel<String>(Inventory.getObject().getComboBoxItems().toArray(new String[0])));
        this.confrm = confirm;
        maleRadioBtn.setSelected(true);
        switchPanels(jPanel2);
        if (confirm.equals("yes")) {
            System.out.println(Employee);
            EmployeeForm.ID = Employee;
            if (Action.equals("Edit")) {
                System.out.println("Here i m");
                this.L = EmployeeList.getObject().getEmployee(ID);
                System.out.println(L.getName());
            } else if (Action.equals("Delete")) {
                //this.ID = Employee;
            }else if(Action.equals("Info")){
                JOptionPane.showMessageDialog(null, Employee +" Are u comedy me?");
            }
        }
        EmployeeDataTable t = new EmployeeDataTable(EmployeeList.getObject().getAllEmployee());
        jTable1.setModel(t);
        
        Action increase = new AbstractAction() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                EmployeeDataTable model = (EmployeeDataTable) table.getModel();
                model.editRow(row);
                switchPanels(EditEmpPanel);
                //nameTxtField1.setText("Rehan");
            }
        };
        ButtonColumn inc = new ButtonColumn(jTable1, increase, 7);
        
        Action deleteAction = new AbstractAction() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                EmployeeDataTable model = (EmployeeDataTable) table.getModel();
                model.deleteRow(row);
                switchPanels(DelEmpPanel);
            }
        };
        ButtonColumn deleteButton = new ButtonColumn(jTable1, deleteAction, 8);
        
        Action infoAction = new AbstractAction() {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                EmployeeDataTable model = (EmployeeDataTable) table.getModel();
                model.infoRow(row);
                  }
        };
        ButtonColumn infoButton = new ButtonColumn(jTable1, infoAction, 6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        addEmpBtn = new javax.swing.JLabel();
        isuStBtn = new javax.swing.JLabel();
        isuLapBtn = new javax.swing.JLabel();
        jLayeredPane = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddEmpPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        cellNoTxtField = new javax.swing.JTextField();
        emailTxtField = new javax.swing.JTextField();
        cnicNoTxtField = new javax.swing.JTextField();
        dobField = new com.toedter.calendar.JDateChooser();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        EditEmpPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cellNoTxtField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        emailTxtField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cnicNoTxtField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dobField1 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        maleRadioBtn1 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        femaleRadioBtn1 = new javax.swing.JRadioButton();
        nameTxtField1 = new javax.swing.JTextField();
        updateBtn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        DelEmpPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        delTxtField = new javax.swing.JTextField();
        delBtn = new javax.swing.JLabel();
        IssueStPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        itemQuantity = new javax.swing.JTextField();
        addListBtn = new javax.swing.JLabel();
        genSlipBtn = new javax.swing.JLabel();
        IssueLapPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        genLapSlipBtn = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEmpMenuItem = new javax.swing.JMenuItem();
        delEmpMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        editMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(816, 626));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        addEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addempbtn.png"))); // NOI18N
        addEmpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmpBtnMouseExited(evt);
            }
        });

        isuStBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isustbtn.png"))); // NOI18N
        isuStBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        isuStBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isuStBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isuStBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isuStBtnMouseExited(evt);
            }
        });

        isuLapBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isulapbtn.png"))); // NOI18N
        isuLapBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        isuLapBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isuLapBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                isuLapBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                isuLapBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isuStBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(isuLapBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addEmpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(addEmpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(isuStBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(isuLapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane.setMaximumSize(new java.awt.Dimension(615, 360));
        jLayeredPane.setName(""); // NOI18N
        jLayeredPane.setPreferredSize(new java.awt.Dimension(615, 360));
        jLayeredPane.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        jLabel7.setBackground(new java.awt.Color(255, 153, 51));
        jLabel7.setFont(new java.awt.Font("Papyrus", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("Manage Your Employees Here......");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jLayeredPane.add(jPanel2, "card7");

        AddEmpPanel.setBackground(new java.awt.Color(250, 242, 242));
        AddEmpPanel.setForeground(new java.awt.Color(250, 242, 242));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Add Employee");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Name");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Gender");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("DOB");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Cell No");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("CNIC No");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Email");

        nameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFieldFocusLost(evt);
            }
        });
        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });

        cellNoTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNoTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNoTxtFieldFocusLost(evt);
            }
        });
        cellNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNoTxtFieldActionPerformed(evt);
            }
        });

        emailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtFieldFocusLost(evt);
            }
        });
        emailTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFieldActionPerformed(evt);
            }
        });

        cnicNoTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicNoTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicNoTxtFieldFocusLost(evt);
            }
        });
        cnicNoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicNoTxtFieldActionPerformed(evt);
            }
        });

        dobField.setMaxSelectableDate(new java.util.Date(253370750495000L));

        buttonGroup1.add(maleRadioBtn);
        maleRadioBtn.setForeground(new java.awt.Color(0, 0, 0));
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleRadioBtn);
        femaleRadioBtn.setForeground(new java.awt.Color(0, 0, 0));
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn.png"))); // NOI18N
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnMouseExited(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setText("Format: (03xx-xxxxxxx)");

        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("Format: (xxxxx-xxxxxxx-x)");

        javax.swing.GroupLayout AddEmpPanelLayout = new javax.swing.GroupLayout(AddEmpPanel);
        AddEmpPanel.setLayout(AddEmpPanelLayout);
        AddEmpPanelLayout.setHorizontalGroup(
            AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmpPanelLayout.createSequentialGroup()
                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEmpPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEmpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(maleRadioBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleRadioBtn)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddEmpPanelLayout.createSequentialGroup()
                                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxtField)
                                    .addComponent(dobField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel32)
                                            .addComponent(cellNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(AddEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel33)
                                            .addComponent(cnicNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEmpPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBtn)
                            .addComponent(jLabel3))
                        .addGap(126, 126, 126)))
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AddEmpPanelLayout.setVerticalGroup(
            AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(AddEmpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(48, 48, 48)
                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(cnicNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddEmpPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cellNoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(AddEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maleRadioBtn)
                    .addComponent(femaleRadioBtn))
                .addGap(31, 31, 31)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLayeredPane.add(AddEmpPanel, "card2");

        EditEmpPanel.setBackground(new java.awt.Color(250, 242, 242));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edit Employee");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        cellNoTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNoTxtField1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Name");

        emailTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtField1ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Gender");

        cnicNoTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicNoTxtField1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("DOB");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Cell No");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("CNIC No");

        buttonGroup1.add(maleRadioBtn1);
        maleRadioBtn1.setForeground(new java.awt.Color(0, 0, 0));
        maleRadioBtn1.setText("Male");
        maleRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtn1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Email");

        buttonGroup1.add(femaleRadioBtn1);
        femaleRadioBtn1.setForeground(new java.awt.Color(0, 0, 0));
        femaleRadioBtn1.setText("Female");
        femaleRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtn1ActionPerformed(evt);
            }
        });

        nameTxtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtField1ActionPerformed(evt);
            }
        });

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/updatebtn1.png"))); // NOI18N
        updateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnMouseExited(evt);
            }
        });

        jButton1.setText("🔄Load Previous Data");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditEmpPanelLayout = new javax.swing.GroupLayout(EditEmpPanel);
        EditEmpPanel.setLayout(EditEmpPanelLayout);
        EditEmpPanelLayout.setHorizontalGroup(
            EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditEmpPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(150, 150, 150)
                                .addComponent(updateBtn)
                                .addGap(0, 81, Short.MAX_VALUE))
                            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxtField1)
                                    .addComponent(dobField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cnicNoTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(cellNoTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(maleRadioBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleRadioBtn1)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(emailTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditEmpPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(159, 159, 159)))
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EditEmpPanelLayout.setVerticalGroup(
            EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(EditEmpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(167, 167, 167))
                    .addGroup(EditEmpPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EditEmpPanelLayout.createSequentialGroup()
                                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel22)
                                    .addComponent(nameTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellNoTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(cnicNoTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dobField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel20)
                            .addComponent(emailTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maleRadioBtn1)
                            .addComponent(femaleRadioBtn1))
                        .addGap(34, 34, 34)))
                .addGroup(EditEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateBtn)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLayeredPane.add(EditEmpPanel, "card2");

        DelEmpPanel.setBackground(new java.awt.Color(250, 242, 242));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Remove Employee");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Please Enter the ID again to confirm");

        delTxtField.setText("EMP-");

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/delbtn.png"))); // NOI18N
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout DelEmpPanelLayout = new javax.swing.GroupLayout(DelEmpPanel);
        DelEmpPanel.setLayout(DelEmpPanelLayout);
        DelEmpPanelLayout.setHorizontalGroup(
            DelEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelEmpPanelLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DelEmpPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DelEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DelEmpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DelEmpPanelLayout.createSequentialGroup()
                        .addComponent(delBtn)
                        .addGap(230, 230, 230))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DelEmpPanelLayout.createSequentialGroup()
                        .addComponent(delTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        DelEmpPanelLayout.setVerticalGroup(
            DelEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DelEmpPanelLayout.createSequentialGroup()
                .addGroup(DelEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DelEmpPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(DelEmpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(delTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(delBtn)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLayeredPane.add(DelEmpPanel, "card2");

        IssueStPanel.setBackground(new java.awt.Color(250, 242, 242));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Issue Stationary");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Enter Quantity");

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Select Stationary Item");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        itemQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQuantityActionPerformed(evt);
            }
        });

        addListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn.png"))); // NOI18N
        addListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addListBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addListBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addListBtnMouseExited(evt);
            }
        });

        genSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn.png"))); // NOI18N
        genSlipBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genSlipBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genSlipBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IssueStPanelLayout = new javax.swing.GroupLayout(IssueStPanel);
        IssueStPanel.setLayout(IssueStPanelLayout);
        IssueStPanelLayout.setHorizontalGroup(
            IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueStPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel26)
                .addGap(100, 100, 100)
                .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addComponent(genSlipBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 187, Short.MAX_VALUE)
                            .addComponent(itemQuantity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(addListBtn)
                        .addGap(22, 22, 22))))
            .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IssueStPanelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel27)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );
        IssueStPanelLayout.setVerticalGroup(
            IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueStPanelLayout.createSequentialGroup()
                .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2))
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGap(4, 4, 4)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(itemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IssueStPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addListBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(genSlipBtn)
                .addGap(44, 44, 44))
            .addGroup(IssueStPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IssueStPanelLayout.createSequentialGroup()
                    .addGap(117, 117, 117)
                    .addComponent(jLabel27)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );

        jLayeredPane.add(IssueStPanel, "card2");

        IssueLapPanel.setBackground(new java.awt.Color(250, 242, 242));
        IssueLapPanel.setMaximumSize(new java.awt.Dimension(615, 360));
        IssueLapPanel.setMinimumSize(new java.awt.Dimension(615, 360));
        IssueLapPanel.setPreferredSize(new java.awt.Dimension(615, 360));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Issue Laptop");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Select the Model ");

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Select the Processor ");

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Select the Generation");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Core i3", "Core i5", "Core i7", "Core i9" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HP", "Lenovo", "Dell", "Toshiba", "Microsoft", "Acer" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3rd", "4th", "5th", "7th", "9th" }));

        genLapSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn.png"))); // NOI18N
        genLapSlipBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genLapSlipBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                genLapSlipBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout IssueLapPanelLayout = new javax.swing.GroupLayout(IssueLapPanel);
        IssueLapPanel.setLayout(IssueLapPanelLayout);
        IssueLapPanelLayout.setHorizontalGroup(
            IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueLapPanelLayout.createSequentialGroup()
                .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueLapPanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel6))
                    .addGroup(IssueLapPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(genLapSlipBtn)
                                .addGroup(IssueLapPanelLayout.createSequentialGroup()
                                    .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel28)
                                        .addComponent(jLabel30))
                                    .addGap(28, 28, 28)
                                    .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        IssueLapPanelLayout.setVerticalGroup(
            IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueLapPanelLayout.createSequentialGroup()
                .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueLapPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IssueLapPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(20, 20, 20)
                .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(IssueLapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(genLapSlipBtn)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLayeredPane.add(IssueLapPanel, "card2");

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLayeredPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");

        addEmpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        addEmpMenuItem.setText("Add an Employee");
        addEmpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addEmpMenuItem);

        delEmpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        delEmpMenuItem.setText("Delete Employee");
        delEmpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delEmpMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(delEmpMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_HOME, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Go to Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        editMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        editMenuItem.setText("Edit Employee");
        editMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(editMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(aboutMenuItem);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Logout🔒");

        logoutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutMenuItem.setText("Log Out");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu5.add(logoutMenuItem);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpMenuItemActionPerformed
        // TODO add your handling code here:
        switchPanels(AddEmpPanel);
    }//GEN-LAST:event_addEmpMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to exit from the System?", "Warning...!", 1);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                EmployeeList.getObject().saveEmloyeeData();
            } catch (Throwable ex) {
                Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Employee Data Failed to save", "⚠ Warning...!!", 1);
            }
            try {
                Inventory.getObject().saveInventory();
            } catch (Throwable ex) {
                Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Inventory Data Failed to save", "⚠ Warning...!!", 1);
            }
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ManagerLogin.getObject().setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void delEmpMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEmpMenuItemActionPerformed
        // TODO add your handling code here:
        if (searchEmp()) {
            switchPanels(DelEmpPanel);
        }
    }//GEN-LAST:event_delEmpMenuItemActionPerformed

    private void editMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuItemActionPerformed
        // TODO add your handling code here:
        if (searchEmp()) {
            switchPanels(EditEmpPanel);
            E = EmployeeList.getObject().getEmployee(ID);
            nameTxtField1.setText(E.getName());
            cellNoTxtField1.setText(E.getCellNo());
            dobField1.setDate(E.getDob());
            cnicNoTxtField1.setText(E.getCnicNo());
            if (E.getGender().equalsIgnoreCase("male")) {
                maleRadioBtn1.setSelected(true);
            } else if (E.getGender().equalsIgnoreCase("female")) {
                femaleRadioBtn1.setSelected(true);
            }
            emailTxtField1.setText(E.getEmail());
        }
    }//GEN-LAST:event_editMenuItemActionPerformed

    private void isuLapBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuLapBtnMouseExited
        // TODO add your handling code here:
        isuLapBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isulapbtn.png")));
    }//GEN-LAST:event_isuLapBtnMouseExited

    private void isuLapBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuLapBtnMouseEntered
        // TODO add your handling code here:
        isuLapBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isulapbtn1.png")));
    }//GEN-LAST:event_isuLapBtnMouseEntered

    private void isuLapBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuLapBtnMouseClicked
        // TODO add your handling code here:
        if (searchEmp()) {
            switchPanels(IssueLapPanel);
        }
    }//GEN-LAST:event_isuLapBtnMouseClicked

    private void isuStBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuStBtnMouseExited
        // TODO add your handling code here:
        isuStBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isustbtn.png")));
    }//GEN-LAST:event_isuStBtnMouseExited

    private void isuStBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuStBtnMouseEntered
        // TODO add your handling code here:
        isuStBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/isustbtn1.png")));
    }//GEN-LAST:event_isuStBtnMouseEntered

    private void isuStBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isuStBtnMouseClicked
        // TODO add your handling code here:
        if (searchEmp()) {
            switchPanels(IssueStPanel);
        }
    }//GEN-LAST:event_isuStBtnMouseClicked

    private void addEmpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseExited
        // TODO add your handling code here:
        addEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addempbtn.png")));
    }//GEN-LAST:event_addEmpBtnMouseExited

    private void addEmpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseEntered
        // TODO add your handling code here:
        addEmpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addempbtn1.png")));
    }//GEN-LAST:event_addEmpBtnMouseEntered

    private void addEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpBtnMouseClicked
        // TODO add your handling code here:
        switchPanels(AddEmpPanel);
    }//GEN-LAST:event_addEmpBtnMouseClicked

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void cellNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNoTxtFieldActionPerformed

    private void emailTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFieldActionPerformed

    private void cnicNoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicNoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicNoTxtFieldActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        // TODO add your handling code here:
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn1.png")));
    }//GEN-LAST:event_addBtnMouseEntered

    private void addBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseExited
        // TODO add your handling code here:
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn.png")));
    }//GEN-LAST:event_addBtnMouseExited

    private void cellNoTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNoTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNoTxtField1ActionPerformed

    private void emailTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtField1ActionPerformed

    private void cnicNoTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicNoTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicNoTxtField1ActionPerformed

    private void maleRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioBtn1ActionPerformed

    private void femaleRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioBtn1ActionPerformed

    private void nameTxtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtField1ActionPerformed

    private void updateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseEntered
        // TODO add your handling code here:
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/updatebtn.png")));
    }//GEN-LAST:event_updateBtnMouseEntered

    private void updateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseExited
        // TODO add your handling code here:
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/updatebtn1.png")));
    }//GEN-LAST:event_updateBtnMouseExited

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        if (V.checkName(nameTxtField.getText()) && V.isValidCellNo(cellNoTxtField.getText()) && V.isValidCNIC(cnicNoTxtField.getText()) && V.isValidEmail(emailTxtField.getText()) && V.checkDateOfBirth(dobField.getDate())) {
            E = new EmployeeData();
            E.setName(nameTxtField.getText());
            E.setCellNo(cellNoTxtField.getText());
            Date date = dobField.getDate();
            E.setDob(date);
            E.setCnicNo(cnicNoTxtField.getText());
            if (maleRadioBtn.isSelected()) {
                E.setGender("Male");
            } else {
                E.setGender("Female");
            }
            E.setEmail(emailTxtField.getText());
            // Emp-ID Generator
            Random rand = new Random();
            int x = rand.nextInt(999);
            E.setEmpID("EMP-" + String.valueOf(x));
            EmployeeList.getObject().addEmployee(E);
            JOptionPane.showMessageDialog(null, "Employee ID: EMP- " + E.getEmpID() + "\nEmployee Succesfully added!!", "Congratualations...", 1);
            EmployeeForm F = new EmployeeForm("helo" ,"helo" ,"no");
            this.setVisible(false);
            F.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Data Entered...!", "⚠ Warning......!!", 1);
        }
    }//GEN-LAST:event_addBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        // TODO add your handling code here:
         if (V.checkName(nameTxtField1.getText()) && V.isValidCellNo(cellNoTxtField1.getText()) && V.isValidCNIC(cnicNoTxtField1.getText()) && V.isValidEmail(emailTxtField1.getText()) && V.checkDateOfBirth(dobField1.getDate())) {
            E = new EmployeeData();
            E.setName(nameTxtField1.getText());
            E.setCellNo(cellNoTxtField1.getText());
            Date date = dobField1.getDate();
            E.setDob(date);
            E.setCnicNo(cnicNoTxtField1.getText());
            if (maleRadioBtn1.isSelected()) {
                E.setGender("Male");
            } else {
                E.setGender("Female");
            }
            E.setEmail(emailTxtField1.getText());
            E.setEmpID(ID);
            EmployeeList.getObject().updateEmployee(ID, E);
            JOptionPane.showMessageDialog(null, "Employee Data Succesfully updated!!", "Congratualations...", 1);
            EmployeeForm F = new EmployeeForm("helo" ,"helo" ,"no");
            this.setVisible(false);
            F.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Data Entered...!", "⚠ Warning......!!", 1);
        }
    }//GEN-LAST:event_updateBtnMouseClicked

    private void delBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseEntered
        // TODO add your handling code here:
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/delbtn1.png")));
    }//GEN-LAST:event_delBtnMouseEntered

    private void delBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseExited
        // TODO add your handling code here:
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/delbtn.png")));
    }//GEN-LAST:event_delBtnMouseExited

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        // TODO add your handling code here:
        System.out.println(delTxtField.getText());
        System.out.println(ID);
        if (delTxtField.getText().equals(ID)) {
            int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to remove this Employee from the System?", "Warning...!", 1);
            if (confirm == JOptionPane.YES_OPTION) {
                EmployeeList.getObject().deleteEmployee(delTxtField.getText());
                JOptionPane.showMessageDialog(null, "Employee Removed Successfully....!", "Delete", 1);
                EmployeeForm F = new EmployeeForm("helo" ,"helo" ,"no");
                this.setVisible(false);
                F.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Employee ID mismatch..!");
        }
    }//GEN-LAST:event_delBtnMouseClicked

    private void itemQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQuantityActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void addListBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addListBtnMouseEntered
        // TODO add your handling code here:
        addListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn1.png")));
    }//GEN-LAST:event_addListBtnMouseEntered

    private void addListBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addListBtnMouseExited
        // TODO add your handling code here:
        addListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/addbtn.png")));
    }//GEN-LAST:event_addListBtnMouseExited

    private void genSlipBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genSlipBtnMouseEntered
        // TODO add your handling code here:
        genSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn1.png")));
    }//GEN-LAST:event_genSlipBtnMouseEntered

    private void genSlipBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genSlipBtnMouseExited
        // TODO add your handling code here:
        genSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn.png")));
    }//GEN-LAST:event_genSlipBtnMouseExited

    private void genLapSlipBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genLapSlipBtnMouseEntered
        // TODO add your handling code here:
        genLapSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn1.png")));
    }//GEN-LAST:event_genLapSlipBtnMouseEntered

    private void genLapSlipBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genLapSlipBtnMouseExited
        // TODO add your handling code here:
        genLapSlipBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buttons/genslipbtn.png")));
    }//GEN-LAST:event_genLapSlipBtnMouseExited

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "This application is made to provide ease \n to an accessories manager of an office\nto manage inventory and employee's data\nApplicaion Owner & Builder: Rehan Pasha\nFor further details contact us @ rehankhalid5544@gmail.com\n\n Powered by Duko Community", "About", 1);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        switchPanels(jPanel2);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void nameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFieldFocusLost
        // TODO add your handling code here:
        if (V.checkName(nameTxtField.getText())) {
            nameTxtField.setBackground(Color.GREEN);
        } else {
            nameTxtField.setBackground(Color.RED);
        }
    }//GEN-LAST:event_nameTxtFieldFocusLost

    private void nameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFieldFocusGained
        // TODO add your handling code here:
        nameTxtField.setBackground(Color.WHITE);
    }//GEN-LAST:event_nameTxtFieldFocusGained

    private void cellNoTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNoTxtFieldFocusLost
        // TODO add your handling code here:
        if (V.isValidCellNo(cellNoTxtField.getText())) {
            cellNoTxtField.setBackground(Color.GREEN);
        } else {
            cellNoTxtField.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cellNoTxtFieldFocusLost

    private void cellNoTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNoTxtFieldFocusGained
        // TODO add your handling code here:
        cellNoTxtField.setBackground(Color.white);
    }//GEN-LAST:event_cellNoTxtFieldFocusGained

    private void cnicNoTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicNoTxtFieldFocusLost
        // TODO add your handling code here:
        if (V.isValidCNIC(cnicNoTxtField.getText())) {
            cnicNoTxtField.setBackground(Color.GREEN);
        } else {
            cnicNoTxtField.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cnicNoTxtFieldFocusLost

    private void cnicNoTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicNoTxtFieldFocusGained
        // TODO add your handling code here:
        cnicNoTxtField.setBackground(Color.white);
        System.out.println(dobField.getDate());
        if (V.checkDateOfBirth(dobField.getDate())) {
            dobField.setBackground(Color.GREEN);
        } else {
            dobField.setBackground(Color.RED);
        }
    }//GEN-LAST:event_cnicNoTxtFieldFocusGained

    private void emailTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFieldFocusLost
        // TODO add your handling code here:
        if (V.isValidEmail(emailTxtField.getText())) {
            emailTxtField.setBackground(Color.GREEN);
        } else {
            emailTxtField.setBackground(Color.RED);
        }
    }//GEN-LAST:event_emailTxtFieldFocusLost

    private void emailTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFieldFocusGained
        // TODO add your handling code here:
        emailTxtField.setBackground(Color.white);
    }//GEN-LAST:event_emailTxtFieldFocusGained

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu.getObject().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nameTxtField1.setText(L.getName());
        cellNoTxtField1.setText(L.getCellNo());
        dobField1.setDate(L.getDob());
        cnicNoTxtField1.setText(L.getCnicNo());
        if (L.getGender().equalsIgnoreCase("male")) {
            maleRadioBtn1.setSelected(true);
        } else if (L.getGender().equalsIgnoreCase("female")) {
            femaleRadioBtn1.setSelected(true);
        }
        emailTxtField1.setText(L.getEmail());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addListBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addListBtnMouseClicked
        // TODO add your handling code here:
        int quant = Integer.parseInt(itemQuantity.getText());
        if(quant <= Inventory.getObject().getAllInventory().get(jComboBox1.getSelectedIndex()).getQuantity()){
            
        }else{
            JOptionPane.showMessageDialog(null, "Stock is less than your Demand");
        }
    }//GEN-LAST:event_addListBtnMouseClicked
    
    public void switchPanels(JPanel panel) {
        jLayeredPane.removeAll();
        jLayeredPane.add(panel);
        jLayeredPane.repaint();
        jLayeredPane.revalidate();
    }
    
    public boolean searchEmp() {
        boolean flag = false;
        this.ID = JOptionPane.showInputDialog(null, "Enter the Employee ID", "Search Employee...", 1);
        for (int i = 0; i < EmployeeList.getObject().getAllEmployee().size(); i++) {
            if (EmployeeList.getObject().getAllEmployee().get(i).getEmpID().equals(ID)) {
                System.out.println("Employee Found");
                flag = true;
                break;
            }
        }
        if (flag == false) {
            JOptionPane.showMessageDialog(null, "Employee Not Found......\nPlease recheck the Employee ID and Try Again\nThank You..! ");
            //searchEmp();
        }
        return flag;
    }

//    public void editTableBtn() {
//        if (this.confrm.equals("yes")) {
//
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEmpPanel;
    private javax.swing.JPanel DelEmpPanel;
    private javax.swing.JPanel EditEmpPanel;
    private javax.swing.JPanel IssueLapPanel;
    private javax.swing.JPanel IssueStPanel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel addEmpBtn;
    private javax.swing.JMenuItem addEmpMenuItem;
    private javax.swing.JLabel addListBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cellNoTxtField;
    private javax.swing.JTextField cellNoTxtField1;
    private javax.swing.JTextField cnicNoTxtField;
    private javax.swing.JTextField cnicNoTxtField1;
    private javax.swing.JLabel delBtn;
    private javax.swing.JMenuItem delEmpMenuItem;
    private javax.swing.JTextField delTxtField;
    private com.toedter.calendar.JDateChooser dobField;
    private com.toedter.calendar.JDateChooser dobField1;
    private javax.swing.JMenuItem editMenuItem;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JTextField emailTxtField1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JRadioButton femaleRadioBtn1;
    private javax.swing.JLabel genLapSlipBtn;
    private javax.swing.JLabel genSlipBtn;
    private javax.swing.JLabel isuLapBtn;
    private javax.swing.JLabel isuStBtn;
    private javax.swing.JTextField itemQuantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JRadioButton maleRadioBtn1;
    private javax.swing.JTextField nameTxtField;
    public javax.swing.JTextField nameTxtField1;
    private javax.swing.JLabel updateBtn;
    // End of variables declaration//GEN-END:variables
}
